version: '2'

services:
  eventeum:
    build: ./
    image: kauri/eventeum
    ports:
    - "8060:8060"
    depends_on:
      - parity
      - mongodb
      - kafka
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_NODE_URL: http://eth-node:8545
      ZOOKEEPER_ADDRESS: zookeeper:2181
      KAFKA_ADDRESSES: kafka:9092
    networks:
      - default

  parity:
    build:
      context: .
      dockerfile: Dockerfile-ParityNode
    ports:
      - "8545:8545"
      - "8180:8180"
      - "8546:8546"
    volumes:
      - $HOME/parity/data:/root/.local/share/io.parity.ethereum
      - $HOME/parity/log:/data/parity-logs
    tty: true
    networks:
      default:
        aliases:
          - eth-node

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb/data/db:/data/db
    networks:
      - default

  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"